services:

  db:
    image: postgres:latest
    env_file: .env.docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d topsbi" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: topsbi-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: python app.py
    volumes:
      - .:/code
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    container_name: topsbi-app

volumes:
  pg_data:
